version: "3.9"

services:
  task-manager:
    restart: always
    user: "${UID}:${GID}"
    image: task-manager-img
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    command: [ "npm", "start" ]

  db:
    image: mysql:8.0.31
    user: "${UID}:${GID}"
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  rabbit:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq/
      - ./data/rabbitmq/log/:/var/log/rabbitmq


  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    volumes:
      - ./docs/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json
